### ISSUE TITLE
Log entry order wrong

### ISSUE THREAD

**Issue by topjor** [tsedio/logger#107]
## Informations

Type | Version
---|---
Bug | 2.x

****

## Description
When using this logging library, log entries do not appear in order.
as can be seen by the timestamps, the log entries are not written out in the right order.

I have put my logger setup and the logfile in this gist:
https://gist.github.com/topjor/5f139f9924505a4754260348b5bacc5b

**Comment by Romakita** [comment]
@topjor I don't understand your issue ...

**Comment by topjor** [comment]
When using this library, and having a file output configured, the individual logs are not in chronological order written out as can be seen.

I think I just figured it out...
I have 2 loggers setup on the same file and it interferes with the order when writing out in an asynchronous matter.

Is there a way for combining loggers, or having different logger names in one logger?

**Comment by Romakita** [comment]
Isn't logical to append logs in the same file from two different loggers...

**Comment by Romakita** [comment]
The logs order isn't important if you use a log entries/kibana. Theses tools will reordering the logs correctly based on the `time` property. Preserve order isn't possible guarantee when you have multiple asynchronous loggers. Isn't there is not needs (excepted for the developer) to preserver order by the timestamp, if you use logstash, kibana or any other log tools.
