### ISSUE TITLE
@tsed/logger-file installation error

### ISSUE THREAD

**Issue by WindBridges** [tsedio/logger#124]
## Informations

Type | Version
---|---
Bug | 6.0.0

****

## Description
As I understand it, to use File Appender with looger, I have to do `npm install @tsed/logger` and then `npm install --save @tsed/logger-file`. However, when I install `@tsed/logger-file` I get the following error:

```
» npm install --save @tsed/logger-file
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test1@1.0.0
npm ERR! Found: @tsed/logger@6.0.0
npm ERR! node_modules/@tsed/logger
npm ERR!   @tsed/logger@"^6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @tsed/logger@"^5.10.0" from @tsed/logger-file@6.0.0
npm ERR! node_modules/@tsed/logger-file
npm ERR!   @tsed/logger-file@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Alex\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Local\npm-cache\_logs\2022-01-09T20_36_42_852Z-debug.log
```

What is the problem?

**Comment by Romakita** [comment]
Maybe just a problem with NPM...
the package exists: https://www.npmjs.com/package/@tsed/logger-file

**Comment by Romakita** [comment]
Hum ok the peerDeps is incorret. you can try with npm i --force @tsed/logger-file. I'll fix the peer dep tomorrow.

See you
Romain

**Comment by WindBridges** [comment]
Ok, thanks. `--force` flag doesn't work, installation is successful, but then I get the error anyway: `Appender file doesn't exists. Check your configuration: {"type":"file","filename":"[...]/app.log","layout":{"type":"json","separator":","}}`

**Comment by Romakita** [comment]
Have you imported the appender ?

```
import "@tsed/logger-file";
```

**Comment by WindBridges** [comment]
Oops, sorry) For some reason I assumed in my mind that the import would be done automatically inside `@tsed/logger`. It's working now.
