### ISSUE TITLE
streams.RollingFileStream is not a constructor

### ISSUE THREAD

**Issue by armandn** [tsedio/logger#180]
The `std` appender works fine but when I tried using the file appender, I get this error:
```
TypeError: streams.RollingFileStream is not a constructor
    at FileAppender.openTheStream (xxx\node_modules\@tsed\logger-file\src\FileAppender.ts:147:6)
    at FileAppender.build (xxx\node_modules\@tsed\logger-file\src\FileAppender.ts:121:24)
    at LoggerAppenders.set (xxx\node_modules\@tsed\logger\src\logger\class\LoggerAppenders.ts:63:16)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1519:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

I used the sample code in the doc.

I even tried manually installing steamroller.

In the `openTheStream` function of the FileAppender file, `streams.RollingFileStream` is undefined.

Node 18.12, TS 4.8.4.
package.jsonn has `type:module`.

tsconfig has
```
        "baseUrl": ".",
        "esModuleInterop": true,
        "moduleResolution": "node",
        "noImplicitAny": true,
        "paths": {"*": ["node_modules/"]},
        "outDir": "dist/",
        "removeComments": true,
        "resolveJsonModule": true,
        "sourceMap": true,
        "strict": true,
        "target": "ESNext",
        "module": "ESNext"

```

**Comment by armandn** [comment]
I fixed it by changing FileAppender from
```
// @ts-ignore
import * as streams from "streamroller";
```
to
```
import streams from "streamroller";
```

I don't fully understand the implications. What was the reasoning for the * import?

**Comment by Romakita** [comment]
hum maybe tsed-logger doesn't use the esModuleInterop option and it explain why you have an error "streams.RollingFileStream is not a constructor".

**Comment by Romakita** [comment]
Ok it's a just a bad import. streamroller is a classic commonjs module so the correct import is `import stream from` (default import instead named import).

The fix is on going ;)
