### ISSUE TITLE
[BUG] Page Pattern layout - /layouts/pattern

### ISSUE THREAD

**Issue by karnavpargi** [tsedio/logger#188]
## Informations

| Type                     |  Version |
| ------------------------ | -------- |
| Bug                       | 2.x      |

---

## Description

Property 'addContext' does not exist on type 'Logger'. Did you mean 'context'?ts(2551)
Logger.d.ts(20, 9): 'context' is declared here.

![Screenshot from 2022-12-05 15-00-59](https://user-images.githubusercontent.com/1001913/205602746-1d4da68d-4a54-453c-9ed9-0c0d3228e5c2.png)

## Todos

- [ ] Example (log, usecase, etc...)
- [x] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hello @karnavpargi 
You’ve right, it’s logger.context.add :)

Thanks for the issue!
