### ISSUE TITLE
Not compatible with browsers

### ISSUE THREAD

**Issue by edwinveldhuizen** [tsedio/logger#236]
## Description

We have a monorepo with ts.ed projects and nextjs projects.
Because we like the logger library, we have been trying to use it in nextjs as well.
With https://nextjs.org/docs/pages/building-your-application/optimizing/instrumentation we've been able to setup the server-side pretty easily with a custom logger.
We've also setup a custom logger for the browser, however due to creating a default instance in `logger/exports` and not giving the ability to import the Logger class on it's own it's throwing the following errors:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'write')
    at <instance_members_initializer> (StdoutAppender.js:38:26)
    at new StdoutAppender (StdoutAppender.js:37:22)
    at LoggerAppenders.set (LoggerAppenders.js:49:26)
    at eval (VM23126 exports.js:9:6)
    at ../node_modules/@tsed/logger/lib/esm/logger/exports.js (_app.js?ts=1710256543066:8786:1)
```

## Todos

- [ ] Allow individual classes to be imported like `import { Logger } from '@tsed/logger/Logger'` bypassing running `logger/exports.js` in the browser

**Comment by Romakita** [comment]
Ok It could be poossible to solve by using exports condition like is it other tsed module. I’ll try to fix that asap.

**Comment by edwinveldhuizen** [comment]
@Romakita that will be awesome! Thanks for the amazingly swift reply as well 🙌

**Comment by Romakita** [comment]
@edwinveldhuizen This PR #237 add conditional exports. The bundler will be able to pick the correct compiled code for your env (browser) ;). You don't need to change your actual implementation ^^ (or maybe instrument webpack/vite/whatever, to use the correct alias).

See you :)
