### ISSUE TITLE
Module '@tsed/logger' does not provide an export named 'colorize'

### ISSUE THREAD

**Issue by lucaspagliari** [tsedio/logger#256]
## Informations

| Type                     |  Version |
| ------------------------ | -------- |
| Bug | 6.7.7   |

---

## Description

When running my tests locally I received the following error:
![image](https://github.com/user-attachments/assets/1f2cd9ab-4b60-4a19-ab3e-bf28279a608f)

I searched about this module and I found out that 6.7.7 version the utils folder was removed from barrelsby.json , that may be causing this error

https://github.com/tsedio/logger/blob/e2efe14c8cfe68d49442fa7e542ddccdbd58ced3/packages/logger/.barrelsby.json#L7-L12

And it is used in @tsed/common in [printRoutes.ts](https://github.com/tsedio/tsed/blob/e6c23a71fcee36dc1d7b8e4bea624c58c037047b/packages/platform/common/src/utils/printRoutes.ts#L1-L2)

## Todos

- [x] Example (log, usecase, etc...)
- [x] Ts.ED version (bug/question)

**Comment by lucaspagliari** [comment]
I went ahead and created a pull request solving this issue, but I'd like to hear what you think about this topic and open to discuss futhermore

**Comment by Romakita** [comment]
@lucaspagliari sorry I haven’t seen your pr before. But thanks for your reactivity ;)
The fix is released !

**Comment by lucaspagliari** [comment]
thanks for you quick response and also for fixing this 😉
